version: '3.1'
services:
    rabbitmq:
            image: "rabbitmq:3-management-alpine"
            ports:
                - 5672:5672
                - 15672:15672
            environment:
                - RABBITMQ_DEFAULT_USER=mhqa 
                - RABBITMQ_DEFAULT_PASS=mhqa
            volumes:
                - /etc/so/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
                - /etc/so/definitions.json:/etc/rabbitmq/definitions.json:ro
    
    dbCliente:
        image: 'postgres:17'
        environment:
          - 'POSTGRES_DB=DB_CLIENTE'
          - 'POSTGRES_PASSWORD=mh8q23pr99'
          - 'POSTGRES_USER=mhqa'
        ports:
          - 5432:5432
        volumes:
          - /app/database/postgre

    dbbancofake:
        image: 'postgres:17'
        environment:
          - 'POSTGRES_DB=DB_BANCOFAKE'
          - 'POSTGRES_PASSWORD=mh8q23pr99'
          - 'POSTGRES_USER=mhqa'
        ports:
          - 5433:5432
        volumes:
          - /app/database/postgre
